# Generated by Django 3.1 on 2021-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210322_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfuser',
            name='fb_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecfuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
