# Generated by Django 3.1 on 2021-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210323_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
