# Generated by Django 3.1 on 2021-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210323_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfuser',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
