# Generated by Django 3.1.7 on 2021-03-28 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ecfuser_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Only Egyptian Phone Numbers.', regex='^(01)[0-9]{9}$')]),
        ),
    ]
