# Generated by Django 3.1 on 2021-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reached',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
