# Generated by Django 3.1.7 on 2021-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210322_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttags',
            name='tag',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
