# Generated by Django 3.1 on 2021-03-22 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210322_1414'),
        ('project', '0002_project_reached'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rates_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserRateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.rate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ecfuser')),
            ],
        ),
    ]
