# Generated by Django 3.1 on 2021-03-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210322_1414'),
        ('project', '0004_comment_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reported',
        ),
        migrations.CreateModel(
            name='ReportedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ecfuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ecfuser')),
            ],
        ),
    ]
