# Generated by Django 3.1 on 2021-03-23 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_featuredprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
