# Generated by Django 3.1.7 on 2021-03-28 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210323_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
